string_x = "THE pinche pastel"
print("Wellcome " + string_x.lower())
print(f"Wellcome {string_x.lower()}")
print("Wellcome {0}".format(string_x.capitalize()))
print(dir(string_x))

#Methods with dir
print(string_x.upper())
print(string_x.swapcase())
print(string_x.lower())
print(string_x.capitalize())
print(string_x.replace("THE", "bye").upper())
print(string_x.count("E"))
print(string_x.count(" "))
print(string_x.startswith("THE"))
print(string_x.endswith("pie"))
print(string_x.split("p"))
print(string_x.find("H"))
print(len(string_x))
print(string_x.index("T"))
print(string_x.isnumeric())
print(string_x.isalpha())
print(string_x.isnumeric())
print(string_x[3])
print(string_x[-1])
print(string_x[-2])
print(string_x[-3])
print(string_x[-4])
print(string_x[-5])
print(string_x[-6])