#region exercise 1

'''If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.
'''

mul = 0
for i in range(1000):
    mul3 = i%3
    mul5 = i%5
    if mul3 == 0 or mul5 == 0:
        mul = mul + i
print(mul)

#endregion

#region exercise 2

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

total=0
def fib(n):
    fibo = []
    for i in range(1,101):
        if i<=2:
            fibo.append(1)
        if i>2:
            x = fibo[i-3]
            y = fibo[i-2]
            z = x + y
            fibo.append(z)
            
    return fibo

num = fib(100)

total = 0
i=0
while num[i]<4000000:
    if num[i]%2==0:
        total = total + num[i]
    i=i+1
print(total)

#endregion

#region exercise 3

'''
The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ?
'''

def Largest_Prime_Factor(n):
    prime_factor = 1
    i = 2

    while i <= n / i:
        if n % i == 0:
            prime_factor = i
            n /= i
        else:
            i += 1

    if prime_factor < n:
        prime_factor = n

    return prime_factor

print(int(Largest_Prime_Factor(600851475143)))

#endregion

#region exercise 4

'''
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
Find the largest palindrome made from the product of two 3-digit numbers.
'''

num_one = 999
num_two = 999
palindromic = []

for i in range(100, num_one+1):
    for j in range(100, num_two+1):
        num = i*j
        if num>=100000:
            c = num%10
            d = (num%100)/10
            d = int(d)
            e = (num%1000)/100
            e = int(e)
            f = (num%10000)/1000
            f = int(f)
            g = (num%100000)/10000
            g = int(g)
            h = (num%1000000)/100000
            h = int(h)

            if (h-c==0 or c-h==0) and (g-d==0 or d-g==0) and (f-e==0 or e-f==0):
                final = num
                palindromic.append(final)

print(int(max(palindromic)))

#endregion

#region exercise 5

'''
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?
'''

def prime(num):
    my_list=list(range(2,num+1))
    n = num
    lista = my_list[::-1]
    while num>0:
        for i in lista:
            if num%i!=0:
                num = num+n
                break
        if i == 2:
            break
    return print(num)

prime(20)

#endregion

#region exercise 6

'''
The sum of the squares of the first ten natural numbers is, 385
The square of the sum of the first ten natural numbers is, 3025
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is .
Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.
'''

num = 100

sum_cua = (num*(num+1)*(2*num+1))/6
sum_nan = (1+num)*(num/2)
sum_nan = sum_nan*sum_nan
total=sum_nan-sum_cua
print(int(total))

#endregion

#region exercise 7

'''
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
What is the 10 001st prime number?
'''

i = 9
ultimo = [2, 3, 5, 7]

while len(ultimo)!=10001:
  j=0
  for j in ultimo:
    if i%j == 0:
      i += 1
      break
  else:
    ultimo.append(i)
    i += 1

print(ultimo.pop())

#endregion

#region exercise 8

'''
The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?
'''

import functools
from functools import reduce
num = 7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450
x = [int(a) for a in str(num)]
resultado_final =[0]
i=0
while i!=1000:
  vec = x[i:i+13]
  if len(vec)==13:
    def multi(x,y):
      return x*y
    resultado = reduce(multi, vec)
    resultado_final.append(resultado)
  i += 1
print(max(resultado_final))

#endregion

#region exercise 9

'''
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a2 + b2 = c2
For example, 32 + 42 = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.
'''

num = 1000
def divisores(n):
  divisores=[1,n]
  lim= int(n**0.5+1)
  for i in range(2,lim):
    if n%i==0: 
      divisores+=[i,n//i]
  divisores.sort()
  return divisores
divisores(1000)

def hallarmn(suma):
  dd=divisores(suma//2)
  for n in dd:
    m= suma/(2*n)-n
    if  n>m  and m>0 :
      return (int(n), int(m))
  return (0,1)

m = hallarmn(num)[0]
n = hallarmn(num)[1]
def ternaspitagoricas(n,m):
  if n>m:
    a = 2*n*m
    b = n**2-m**2
    c = n**2+m**2
    return a*b*c
print(ternaspitagoricas(m, n))

#endregion

#region exercise 10

'''
The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.
'''

import math as m
prime = [x for x in range(2, 2000000) if all(x % y != 0 for y in range(2, int(m.sqrt(x)) + 1))]
print(sum(prime))

#endregion

#region exercise 11

'''
In the 20 X 20 grid below, four numbers along a diagonal line have been marked in red

08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48

The product of these numbers is 26 X 63 X 78 X 14 = 1788696.

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20 X 20 grid?
'''

import math
import numpy as np
num = '08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65 52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80 24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50 32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70 67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21 24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72 21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95 78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92 16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57 86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58 19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40 04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66 88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69 04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16 20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54 01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48'
num = [int(n) for n in num.split()]

n = int(math.sqrt(len(num)))

if n ** 2 != len(num):
    print("La longitud de la lista no es un cuadrado perfecto. No se puede crear una matriz nxn.")
else:
  list_num = []  
  for i in range(1, n+1):
      list_num.append(num[n*(i-1):i*n])
      

matriz = np.array(list_num)
greatest = []

# Rows direction left right
for i in range(0, n):
    fila = list((matriz[i])) 
    while len(fila) >=4:
        list_four = fila[0:4]
        result = np.prod(list_four)
        greatest.append(result)
        first = fila.pop(0)

# Rows direction right left
for i in range(0, n):
    fila = list((matriz[i])) 
    while len(fila) >=4:
        list_four = fila[-4::]
        result = np.prod(list_four)
        greatest.append(result)
        first = fila.pop()

# Columns direction bottom up
for i in range(0, n):
    columna = ([fila[i] for fila in matriz])
    while len(columna) >=4:
        list_four = columna[-4::]
        result = np.prod(list_four)
        greatest.append(result)
        first = columna.pop()

# Columns up and down
for i in range(0, n):
    columna = ([fila[i] for fila in matriz])
    while len(columna) >=4:
        list_four = columna[0:4]
        result = np.prod(list_four)
        greatest.append(result)
        first = columna.pop(0)

# Main diagonal above
fila = 1
columna = 0
for i in range(1, n+1):
    columna += 1
    diagonal = list(np.diagonal(matriz, offset=columna-fila))
   
    while len(diagonal) >=4:
        list_four = diagonal[0:4]
        result = np.prod(list_four)
        greatest.append(result)

        first = diagonal.pop(0)

# Main diagonal below
fila = 1
columna = 0
for i in range(1, n+1):
    columna += 1
    diagonal = list(np.diagonal(matriz, offset=columna-fila))
   
    while len(diagonal) >=4:
        list_four = diagonal[-4::]
        result = np.prod(list_four)
        greatest.append(result)

        first = diagonal.pop()    

# Reverse diagonal from top to bottom
fila = 1
columna = 1
for i in range(1, n):
    fila += 1
    diagonal = list(np.diagonal(matriz, offset=columna-fila))

    while len(diagonal) >=4:
        list_four = diagonal[-4::]
        result = np.prod(list_four)
        greatest.append(result)

        first = diagonal.pop()

# Reverse diagonal from top to bottom
fila = 1
columna = 1
for i in range(1, n):
    fila += 1
    diagonal = list(np.diagonal(matriz, offset=columna-fila))

    while len(diagonal) >=4:
        list_four = diagonal[0:4]
        result = np.prod(list_four)
        greatest.append(result)

        first = diagonal.pop(0)

# Previous calculations of secondary diagonals
matriz = np.rot90(matriz)

fila = 1
columna = 0
for i in range(1, n+1):
    columna += 1
    diagonal = list(np.diagonal(matriz, offset=columna-fila))
   
    while len(diagonal) >=4:
        list_four = diagonal[0:4]
        result = np.prod(list_four)
        greatest.append(result)

        first = diagonal.pop(0)

fila = 1
columna = 0
for i in range(1, n+1):
    columna += 1
    diagonal = list(np.diagonal(matriz, offset=columna-fila))
   
    while len(diagonal) >=4:
        list_four = diagonal[-4::]
        result = np.prod(list_four)
        greatest.append(result)

        first = diagonal.pop()    

fila = 1
columna = 1
for i in range(1, n):
    fila += 1
    diagonal = list(np.diagonal(matriz, offset=columna-fila))

    while len(diagonal) >=4:
        list_four = diagonal[-4::]
        result = np.prod(list_four)
        greatest.append(result)

        first = diagonal.pop()

fila = 1
columna = 1
for i in range(1, n):
    fila += 1
    diagonal = list(np.diagonal(matriz, offset=columna-fila))

    while len(diagonal) >=4:
        list_four = diagonal[0:4]
        result = np.prod(list_four)
        greatest.append(result)

        first = diagonal.pop(0)

print(max(greatest))

#endregion

#region exercise 12

'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
1+2+3+4+5+6+7=28. The first ten terms would be: 1,3,6,10,15,21,28,45,55,...
Let us list the factors of the first seven triangle numbers:
1: 1
3: 1, 3
6: 1, 2, 3, 6
10: 1, 2, 5, 10
15: 1, 3, 5, 15
28: 1, 2, 4, 7, 14, 28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''

import math

num = 0
sum_num = 0
factors_num = []

while len(factors_num) < 500:
    num += 1
    sum_num += num
    max_num = sum_num
    factors_num = []

    for i in range(1, int(math.sqrt(max_num)) + 1):
        if max_num % i == 0:
            factors_num.append(i)
            if i != max_num // i:  # Asegúrate de no contar el mismo factor dos veces
                factors_num.append(max_num // i)

print(factors_num)
print(max_num)

#endregion